Wait for a11y-results to be created

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -36,9 +36,24 @@ pipeline {
     post {
         always {
             script {
-                
+                // Wait for the a11y-results directory to be created
                 dir('axe-reports-jenkins') {
-                    sh 'ls -la ./a11y-results'
+                    sh '''
+                    COUNTER=0
+                    while [ ! -d "./a11y-results" ] && [ $COUNTER -lt 30 ]; do
+                        echo "Waiting for a11y-results directory to be created..."
+                        sleep 1
+                        COUNTER=$((COUNTER+1))
+                    done
+                    if [ ! -d "./a11y-results" ]; then
+                        echo "a11y-results directory not found after waiting"
+                        exit 1
+                    fi
+                    '''
+                }
+                // List the contents of the a11y-results directory
+                dir('axe-reports-jenkins') {
+                    sh 'ls -la ./a11y-results || echo "No results found"'
                 }
                 // Archive the a11y results
                 dir('axe-reports-jenkins') {
